### ISSUE TITLE
Open an issue per each translatable unit.

### ISSUE THREAD

**Issue by goyox86** [thecodix/book#3]
What do you think about creating an issue per each chapter on the book here. Creating a tag and attaching it to them so it would be super easy for us to track who is doing what and for newcomers to just pick one of those and just start right away.

Is just matter of going trough the TOC and creating one issue here.

Thoughts?

**Comment by thecodix** [comment]
Yes, but be sure to add a tag 'chapter' or something like that for easily arranging them when they start to pile up

**Comment by goyox86** [comment]
Indeed, that's why I suggested adding the tag.

**Comment by thecodix** [comment]
Perfect, you wanna get to it?

**Comment by goyox86** [comment]
Sure!

**Comment by thecodix** [comment]
Hey, how is it going people? I see not many updates lately

**Comment by goyox86** [comment]
Sorry @thecodix I've been busy but tomorrow I'll do it!
