### ISSUE TITLE
Coordination Meeting?

### ISSUE THREAD

**Issue by sebasmagri** [thecodix/book#4]
Hi! Should we do a coordination meeting?

I propose using the #rust-es IRC channel for this. I'd like to briefly discuss how can we cooperate on the translation work, a glossary and a review process.

My idea is to use this experience to standardize some guidelines for translations across other content based products of the Rust project.

Regards,

**Comment by thecodix** [comment]
Sounds good, let's check what the others have to say about it

**Comment by thecodix** [comment]
As an alternative, you may configure a hipchat room so we don't miss on updates

**Comment by sebasmagri** [comment]
@thecodix I'd really prefer to use the IRC channel. It's easily accessible (with history/backlog) via Matrix/RIOT if you don't like IRC clients.

**Comment by goyox86** [comment]
I'm in with IRC too. Just set a date and I'll be there!

**Comment by thecodix** [comment]
I'm in as well, if people is available today, it can be at a late UTC time

**Comment by sebasmagri** [comment]
@thecodix @goyox86 are you going to be available on IRC this weekend?

**Comment by goyox86** [comment]
Hi people sorry I wasn't there on weekend. I'm gonna be online all the week if you decide to it. Maybe setting a date would be better so we adapt our schedules.

**Comment by thecodix** [comment]
Thursday 9 august, 20pm UTC good for everyone?
Just chose it arbitrarily

**Comment by goyox86** [comment]
What a bad luck I'm gonna be in the middle of the Atlantic haha. Could it be 11th?

**Comment by thecodix** [comment]
Sunday 13 might be better, 20pm UTC?
